### ISSUE TITLE
Pacakge both this and DTO in one plugin

### ISSUE THREAD

**Issue by weedkiller** [yohney/common-refactorings-plugin#1]
Hi, it would be nice to have both of them in one plug-in, and a check box for the features.

This is much more light weight that reshaper etc 👍

**Comment by yohney** [comment]
This one I'm not keen on maintaining, just created it for my specific case. It has some errors if multiple classes are in same file. 

Also, as you mentioned, it is much more lightweight than resharper, and packaging it together might also cause it to become a bit massive. 

At some point, I might package each of this minor code refactorings as a separate plugin, so you would just include ones you need in visual studio.

**Comment by weedkiller** [comment]
frankly this is nicer DTO generator than reshaper!
